### ISSUE TITLE
Future development

### ISSUE THREAD

**Issue by qpowell** [konradjurk/ember-text-highlight#12]
Hi, @konradjurk is this project still being actively maintained?

**Comment by konradjurk** [comment]
Hey @qpowell, it is not actively maintained and I wouldn't recommend to start using it in its current state. However, since it seems to be in use, I do have to spend time in the future to improve its security e.g. by using lit-html internally which should easily and performantly circumvent Javascript injection.

**Comment by qpowell** [comment]
> Hey @qpowell, it is not actively maintained and I wouldn't recommend to start using it in its current state. However, since it seems to be in use, I do have to spend time in the future to improve its security e.g. by using lit-html internally which should easily and performantly circumvent Javascript injection.

Thanks for the clarification! I noticed a security issue, but didn't see anything in the README advising people not to use this in it's current state, so I wanted to clarify. Something like that may be helpful for future visitors to the repo 👍🏾

**Comment by konradjurk** [comment]
@qpowell You are absolutely right, there should be a hint -- and there is now! 

I'll try to find some time in the next weeks to update this plugin to be safe to use.
